server:
  port: 8010
spring:
  application:
    name: @pom.artifactId@
  profiles:
    active:
      - @profileActive@
      - secure

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

info:
  owner: tigerphz
  version: @project.version@

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    instance:
      # docker 部署开启
      prefer-ip-address: true
      status-page-url-path: /actuator/info
      health-check-url-path: /actuator/health
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

logging:
  level.root: info
  path: logs/
  file: ${spring.application.name}.log

---
# 不安全配置
spring:
  profiles: insecure
---
# 安全配置 admin登录的用户名和密码
spring:
  profiles: secure
  security:
    user:
      name: admin
      password: admin
  boot:
      admin:
        client:
          username: ${spring.security.user.name}       #These two are needed so that the client
          password: ${spring.security.user.password}   #can register at the protected server api
# 注册给eureka的时候告诉eureka自己的密码
eureka:
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}         #These two are needed so that the server
      user.password: ${spring.security.user.password} #can access the protected client endpoints

