server:
  port: 8070
spring:
  profiles:
    active: @profileActive@
  application:
    name: @pom.artifactId@
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: tgcloud-config
        uri: lb://tgcloud-config
        order: 8000
        predicates:
        - Path=/test/**
        filters:
        - StripPrefix=1

info:
  owner: tigerphz
  version: @project.version@

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    instance:
      # docker 部署开启
      prefer-ip-address: true
      status-page-url-path: /actuator/info
      health-check-url-path: /actuator/health
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
logging:
  level.root: info
  path: logs/
  file: ${spring.application.name}.log

