server:
  port: 7979
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  profiles:
    active: @profileActive@
  application:
    name: @pom.artifactId@
  redis:
    host: localhost
    port: 6379
    # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    timeout: 60s
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  boot:
    admin:
      client:
        #如果Admin端设置了用户名密码访问，你也需要在客户端配置它们
        username: admin
        password: admin
        instance:
          #当前应用程序名字
          name: @pom.artifactId@
          #客户端是否提供本机真实ip
          prefer-ip: true
  security:
    user:
      name: admin
      password: admin


#客户端版本号，在监控中心显示
info:
  owner: tigerphz
  version: @project.version@

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  forceOriginalQueryStringEncoding: true
  routes:
    aus-route:
      path: /aus/**
      sensitiveHeaders:
      service-id: tgcloud-security-authserver
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
    admin-route:
      path: /admin/**
      sensitiveHeaders:
      service-id: tgcloud-microservice-admin
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
  add-proxy-headers: true
  add-host-header: true
hystrix:
  propagate:
    request-attribute:
      enabled: true
  command:
    default:
      execution:
        timeout:
          #hystrix 的超时时间
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 120000
ribbon:
  eager-load:
    enabled: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
  ConnectTimeout: 10000
  ReadTimeout: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    instance:
      # docker 部署开启
      prefer-ip-address: true
      status-page-url-path: /actuator/info
      health-check-url-path: /actuator/health
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

security:
  oauth2:
    client:
      clientId: tgcloud-client-gateway
      clientSecret: tgcloudClientSecret
      access-token-uri: http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:7979}/aus/oauth/token
      user-authorization-uri: http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:7979}/aus/oauth/authorize
    resource:
      user-info-uri: http://localhost:8999/user
      prefer-token-info: false
      jwt:
        key-uri: http://localhost:8999/oauth/token_key

proxy:
  auth:
    routes:
      aus-route: oauth2

logging:
  level.root: info
  path: logs/
  file: ${spring.application.name}.log
tgcloud:
  enableSqlLogInterceptor: false
