server:
  port: 8011
spring:
  application:
    name: @pom.artifactId@
  profiles:
    active:
      - @profileActive@
      - secure

info:
  owner: tigerphz
  version: @project.version@

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    instance:
      # docker 部署开启
      prefer-ip-address: true
      status-page-url-path: /actuator/info
      health-check-url-path: /actuator/health
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

logging:
  level.root: info
  path: logs/
  file: ${spring.application.name}.log

#去除控制台异常
management:
  metrics:
    web:
      server:
        auto-time-requests: false


