server:
  port: 8011
spring:
  application:
    name: @pom.artifactId@
  profiles:
    active:
      - @profileActive@
#zipkin数据保存到数据库中需要进行如下配置
#表示当前程序不使用sleuth
  sleuth:
    enabled: false
#数据库脚本创建地址，当有多个时可使用[x]表示集合第几个元素，脚本可到官网下载，需要先手动到数据库执行
#  datasource:
#    schema[0]: classpath:/zipkin.sql
#spring boot数据源配置
#    url: jdbc:mysql://localhost:3306/tgcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
#    username: tiger
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    continue-on-error: true
#表示zipkin数据存储方式是mysql
#zipkin:
#  storage:
#    type: mysql

info:
  owner: tigerphz
  version: @project.version@

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    instance:
      # docker 部署开启
      prefer-ip-address: true
      status-page-url-path: /actuator/info
      health-check-url-path: /actuator/health
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

logging:
  level.root: info
  path: logs/
  file: ${spring.application.name}.log

#去除控制台异常
management:
  metrics:
    web:
      server:
        auto-time-requests: false


